services:
    core.base_filter:
        class: CoreBundle\Filter\Filter
        arguments: ['@translator']
        public: false

    core.date_filter:
        class: CoreBundle\Filter\DateFilter
        parent: core.base_filter
        public: false

    core.type_filter:
        class: CoreBundle\Filter\TypeFilter
        parent: core.base_filter
        arguments: ['@core.type_repository']
        public: true

    core.configuration_filter:
        class: CoreBundle\Filter\ConfigurationFilter
        parent: core.date_filter
        arguments: ['@core.configuration_repository']
        public: true
