services:
    core.send_notification:
        class: CoreBundle\Service\SendNotification
        arguments: ['@core.email_notification', '@translator']

    core.email_notification:
        class: CoreBundle\Service\Notification\EmailNotification
        arguments: ['@mailer']
