default:
    type:     rest
    resource: CoreBundle\Controller\DefaultController

type:
    type:     rest
    resource: CoreBundle\Controller\TypeController

configuration:
    type:     rest
    resource: CoreBundle\Controller\ConfigurationController
