default:
    type:     rest
    resource: CoreBundle\Controller\DefaultController

type:
    type:     rest
    resource: CoreBundle\Controller\TypeController

configuration:
    type:     rest
    resource: CoreBundle\Controller\ConfigurationController

garden:
    type:     rest
    resource: CoreBundle\Controller\GardenController

measure:
    type:     rest
    resource: CoreBundle\Controller\MeasureController

garden_configuration:
    type:     rest
    parent:   garden
    resource: CoreBundle\Controller\GardenConfigurationController

garden_access:
    type:     rest
    parent:   garden
    resource: CoreBundle\Controller\GardenAccessController
