default:
    type:     rest
    resource: CoreBundle\Controller\DefaultController

type:
    type:     rest
    resource: CoreBundle\Controller\TypeController

configuration:
    type:     rest
    resource: CoreBundle\Controller\ConfigurationController

garden:
    type:     rest
    resource: CoreBundle\Controller\GardenController

measure:
    type:     rest
    resource: CoreBundle\Controller\MeasureController

access:
    type:     rest
    resource: CoreBundle\Controller\AccessController
