services:
    core.base_voter:
        class: CoreBundle\Security\Voter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    type.voter:
        class: CoreBundle\Security\TypeVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }

    garden.voter:
        class: CoreBundle\Security\GardenVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }

    configuration.voter:
        class: CoreBundle\Security\ConfigurationVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }

    alert.voter:
        class: CoreBundle\Security\AlertVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }
