services:
    core.base_voter:
        class: CoreBundle\Security\Voter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    type.type_voter:
        class: CoreBundle\Security\TypeVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }
